version: v2.1.2

plugins:
  - module: "github.com/Komissarich/loglinter"
    path: .
    import: "github.com/Komissarich/loglinter/plugins"
    analyzers:
      - name: loglinter
        description: "Checks that all logs uses english letters, starts with lowercase letter, doesnt have special symbols or emoji, doesnt have critical info"
