version: "2"

linters:
  enable:
    - loglinter

linters-settings:
  custom:
    - name: loglinter
      path: github.com/Komissarich/loglinter
      description: "Проверяет логи на английский, отсутствие кириллицы, эмодзи, критических данных"
      type: module
